const typeError = {
   
    ERROR_ARGUMENTOS_INVALIDOS : 400 ,
    ERROR_DATOS : 400 ,
    ERROR_AUTENTICACION : 401 ,
    ERROR_AUTORIZACION : 403 ,
    ERROR_RECUSO_NO_ENCONTRADO : 404 ,
    REDIRECTION : 302



}

module.exports = typeError