config:
  # plugins:
  #   metrics-by-endpoint: {}
  target: 'http://localhost:8080'
  phases:
    - duration: 20
      arrivalRate: 5
      rampTo: 20
      name: "Prueba rendimiento Login / Registro"
scenarios:
  - name: "Sessions Flow (registro + login)"
    flow:
      - log: "Creamos las variables para el usuario de prueba"
      - get:
          url: "/mockingproducts"
          capture:
            - json: "$.usuario.nombre"
              as: "nombre"
            - json: "$.usuario.apellido"
              as: "apellido"
            - json: "$.usuario.email"
              as: "email"
            - json: "$.usuario.password"
              as: "password"
            - json: "$.usuario.edad"
              as: "edad"
      - log: "Registro de usuario {{nombre}} {{apellido}}"
      - post:
          url: "/api/sessions/register"
          json:
            nombre: "{{nombre}}"
            apellido: "{{apellido}}"
            email: "{{email}}"
            edad: "{{edad}}"
            password: "{{password}}"
      - think: 2
      - log: "Login {{email}}"
      - post:
          url: "/api/sessions/login"
          json:
            email: "{{email}}"
            password: "{{password}}"